### ISSUE TITLE
Closing with red x doesn't reopen files

### ISSUE THREAD

**Issue by ari62** [CodingFriends/Tincta#61] opened 2021-12-31 04:08 UTC
When I right click on the icon in the dock and quit, then reopen tincta, my previously opened files are opened again. When I close with the red x button, which i think doesn't fully quit, then reopen by click on the tincta icon, my previously opened files are not opened and I have a new untitled file opened instead.

I am using and 2021 macbook pro 16-inch with macOS Monterey Version 12.1

**Comment by ari62** [comment] 2021-12-31 04:12
Note I see the same issue in another text editor I am trying.

**Comment by greimers** [comment] 2021-12-31 12:49
Thanks for your feedback.

This is actually not a bug but a feature. On the Mac there is a distinction between closing windows and quitting an app.
When you close the Tincta window using the red button or selecting _Close_ from the menu, this will close the window and all open documents. Clicking the Tincta icon again, will create a new blank document. 
This behavior might differ between apps, but closing all tabs and documents when closing the window is the usual behavior on the Mac. For example Firefox and Safari also close all tabs when you close the window.

**Closed by greimers** 2021-12-31 12:49 UTC
Labels: wontfix
